#!SCons

"""	Scons script for build urth externals libraries. """

__author__ = "*nixCoders team"
__url__ = "http://www.nixcoders.org/"
__copyright__ = "Copyright (C) 2007 - *nixCoders team"
__license__ = """
	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2, or (at your option)
	any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software Foundation,
	Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
"""

import os

Import('env')

# Check for needed builder, else add it
if not env['BUILDERS'].has_key('LibBuilder'):
	env.Tool('lib_builder', toolpath=['../scons'])

# ioq3 stuff
IOQ3_SVN = 'svn://svn.icculus.org/quake3/trunk'
IOQ3_REVISION = 995	# Known as 1.34
# Get ioq3 source and modify it to avoid multiple same declaration
ioq3Svn = env.Command(
	action="""
		svn checkout -r%i %s ioq3;
																	\
		sed	-e '1i\#ifndef CG_PUBLIC_H_\\n#define CG_PUBLIC_H_'		\
			-e '$$a#endif'											\
			-i ioq3/code/cgame/cg_public.h;						\
																	\
		sed	-i ioq3/code/game/bg_public.h							\
			-e '1i\#ifndef BG_PUBLIC_H_\\n#define BG_PUBLIC_H_'		\
			-e '$$a#endif';											\
																	\
		sed -i ioq3/code/renderer/tr_local.h						\
			-e 's/\\(orientationr_t\\s*\\**\\)or/\\1orientation/'	\
	""" % (IOQ3_REVISION, IOQ3_SVN),
	target=Dir('ioq3'),
	source=Value(str(IOQ3_REVISION)),
	chdir=Dir('.').path
)

# Add local install to the environment paths only if libs is not going to be build
if not 'libs' in COMMAND_LINE_TARGETS:
	env.Append(
		CPPPATH=[os.path.join(env['LIBS_PREFIX'], 'include')],
		LIBPATH=[os.path.join(env['LIBS_PREFIX'], 'lib')]
	)
# else add libs builders
else:
	Alias(
		'libs',
		ioq3Svn
	)
